#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.svg"
# use `px` or `x` with logo_width, example: "100px".
# Note: logo_width is not work with .svg file
logo_width = "257px"
# if logo_webp set false, it will not generate WEBP version of logo
logo_webp = true # default is true
# logo text will only show when logo is missing.
logo_text = "4D Platform"
# image gallery shortcode
image_gallery = true

# footer information
footer_info = "The content of this site, 4D Platform, 4D coin, 4D-NFT are properties of the 4D Foundation."

# contact form action
contact_form_action = "https://formspree.io/f/xgernlzd" # contact form works with https://formspree.io

# career form action
career_form_action = "#" # career form works with https://formspree.io

# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script= "" 

# Main Sections
mainSections= ["blog"]

# contact information
[contact_info]
address = " 7385 N State Rt 3, PMB 3005, Westerville, OH 43082"
phone = ["+1 202 750 4025"]
email = ["info@4dco.in"]

# imaging processing
[imaging]
# Default JPEG or WebP quality setting. Default is 100.
quality = 100

# Preloader
[preloader]
enable = true
preloader = "images/favicon.png" # use jpg, png, svg or gif format.

# Navigation button
[navigation_button]
enable = true
label = "Sign Up Now"
link = "signup/"

# seo meta data for OpenGraph / Twitter Card
[metadata]
keywords = ["4D Platform", "ICO", "diamonds"]
description = "4D platform, Investment in Diamonds Made Smart and Accessible"
author = "4D Foundation"
image = "images/og-image.jpg" # this image will be used as fallback if a page has no image of its own

# matomo tracking: see https://matomo.org/
[matomo]
enable = false
url = "" # your matomo url
id = "" # your matomo id

# baidu analytics: see https://tongji.baidu.com/
[baidu]
enable = false
analytics_id = "" # Your ID

# plausible analytics: see https://plausible.io/
[plausible]
enable = false
domain = "" # yourdomain.com

# counter analytics: see https://counter.dev/setup.html
[counter]
enable = false
username = "" # your username

# site verifications
[site_verification]
google = "" # Your verification code
bing = "" # Your verification code
baidu = "" # Your verification code
facebook = "" # Your verification code

# cookies
[cookies]
enable = true
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

# call-to-action
[cta]
enable = true
title = "Learn more about the opportunity"
content = "The White Paper provides detailed information on the business processes behind the 4D Platform."
button = "Download the White Paper"
button_link = "/"

############################# social site ########################
[[social]]
title = "4D Platform"
icon = "lab la-facebook-f" # https://icons8.com/line-awesome
link = "#!"

[[social]]
title = "4D PlatformTweet"
icon = "lab la-twitter" # https://icons8.com/line-awesome
link = "#!"

[[social]]
title = "4D PlatformIn"
icon = "lab la-linkedin-in" # https://icons8.com/line-awesome
link = "#!"

[[social]]
title = "4D PlatformPin"
icon = "lab la-pinterest" # https://icons8.com/line-awesome
link = "#!"